// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX4Sk0hRAsaYusv5nnus570QKmYdNrCPg',
    appId: '1:284124815253:web:2f91e5dfab306f0c92609c',
    messagingSenderId: '284124815253',
    projectId: 'nti9-af3f4',
    authDomain: 'nti9-af3f4.firebaseapp.com',
    storageBucket: 'nti9-af3f4.firebasestorage.app',
    measurementId: 'G-S4MG8EPVKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu7LayM91xv9FLHb3HgOh78LBuY6c0I7Y',
    appId: '1:284124815253:android:0bde6b1bab35e1e192609c',
    messagingSenderId: '284124815253',
    projectId: 'nti9-af3f4',
    storageBucket: 'nti9-af3f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkhxUA7hp6Ox59EUG810r0zqeLhJUg7vc',
    appId: '1:284124815253:ios:214a9bbecfb17e1192609c',
    messagingSenderId: '284124815253',
    projectId: 'nti9-af3f4',
    storageBucket: 'nti9-af3f4.firebasestorage.app',
    iosBundleId: 'com.example.nti9Firebase',
  );
}
